backtraces_path = "~/.local/state/neovide_backtraces.log" # see below for the default platform specific location
fork = true
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = false
vsync = true
wsl = false

[font]
size = 13.5
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono NF Thin" # Will use the bundled Fira Code Nerd Font by default
style = "Thin"

[[font.bold]]
family = "JetBrainsMono NF SemiBold" # Will use the bundled Fira Code Nerd Font by default
style = "SemiBold"

[[font.italic]]
family = "JetBrainsMono NF Thin" # Will use the bundled Fira Code Nerd Font by default
style = "Thin Italic"

[[font.bold_italic]]
family = "JetBrainsMono NF SemiBold" # Will use the bundled Fira Code Nerd Font by default
style = "SemiBold Italic"
