backtraces_path = "~/.local/state/neovide_backtraces.log" # see below for the default platform specific location
fork = true
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
size = 14.0
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font Mono" # Will use the bundled Fira Code Nerd Font by default
style = "ExtraLight"

[[font.bold]]
family = "JetBrainsMono Nerd Font Mono" # Will use the bundled Fira Code Nerd Font by default
style = "Bold"

[[font.italic]]
family = "JetBrainsMono Nerd Font Mono" # Will use the bundled Fira Code Nerd Font by default
style = "ExtraLight Italic"

[[font.bold_italic]]
family = "JetBrainsMono Nerd Font Mono" # Will use the bundled Fira Code Nerd Font by default
style = "Bold Italic"
